# Generated by Django 3.2.8 on 2021-11-01 08:08

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211031_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessname',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 8, 8, 32, 533668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='businessname',
            name='last_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 8, 8, 32, 533685, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='corporateowner',
            name='identification',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='corporateowner',
            name='photograph',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='corporateowner',
            name='signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
