# Generated by Django 3.2.8 on 2021-11-01 08:09

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211101_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestee',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attestee',
            name='means_of_identification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attestee',
            name='residential_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='businessname',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 8, 9, 41, 822930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='businessname',
            name='last_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 8, 9, 41, 822947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='individualowner',
            name='identification',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='individualowner',
            name='photograph',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='individualowner',
            name='signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
