# Generated by Django 3.2.8 on 2021-11-02 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211101_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessname',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 18, 10, 49, 744165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='businessname',
            name='last_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 18, 10, 49, 744181, tzinfo=utc)),
        ),
    ]
