# Generated by Django 3.2.8 on 2021-11-02 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20211102_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessname',
            name='attestee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.attestee'),
        ),
        migrations.AlterField(
            model_name='businessname',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 18, 13, 54, 51362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='businessname',
            name='last_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 2, 18, 13, 54, 51379, tzinfo=utc)),
        ),
    ]
